# This is a basic workflow to help you get started with Actions

name: CreateBranch

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source Branch'     
        required: true
        default: 'main'
      target_branch:
        description: 'Target Branch'
        required: true
        default: 'release-vX'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create Branch
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          set -xe
          SRC_BRANCH=${{ github.event.inputs.source_branch }} 
          TARGET_BRANCH=${{ github.event.inputs.target_branch }}

          gh_repo_names=$(cat target_repo_name.txt)
          for repo_name in ${gh_repo_names}; do
            echo "Promoting ${repo_name} $SRC_BRANCH to $TARGET_BRANCH"
            git clone https://$API_TOKEN_GITHUB@github.com/zugwan/${repo_name}.git -b $SRC_BRANCH
            cd ${repo_name}
            git checkout -b $TARGET_BRANCH
            git push origin $TARGET_BRANCH
            cd -
          done
