# This is a basic workflow to help you get started with Actions

name: CreateTAG

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source Branch'     
        required: true
        default: 'release-vX'
      tag_name:
        description: 'Tag Name'
        required: true
        default: 'vX.Y.Z'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create TAG
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          set -xe
          SRC_BRANCH=${{ github.event.inputs.source_branch }} 
          TAG=${{ github.event.inputs.tag_name }}

          git config --global user.email "taco_support@sk.com"
          git config --global user.name "Ahn Ahn"

          gh_repo_names=$(cat target_repo_name.txt)
          for repo_name in ${gh_repo_names}; do
            echo "Creating Tag $TAG in $SRC_BRANCH HEAD of ${repo_name}"
            git clone https://$API_TOKEN_GITHUB@github.com/zugwan/${repo_name}.git -b $SRC_BRANCH
            cd ${repo_name}
            git tag $TAG -m "release ${TAG}"
            git push origin --tags
            cd -
          done
